
STRINGS.NAMES.BAG = "包裹" --物品名称
STRINGS.RECIPE_DESC.BAG = "不应该能够制作的包裹啊" --制作描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BAG = "可以种植地上" --检查描述

STRINGS.NAMES.TIMEBOMB = "不可丢弃的定时炸弹" --物品名称
STRINGS.RECIPE_DESC.TIMEBOMB = "不应该能够制作啊" --制作描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIMEBOMB = "三十秒内会爆炸，不能丢弃，但可转交" --检查描述

STRINGS.NAMES.BLACK_HOLE_OF = "黑洞？？"

STRINGS.NAMES.CLEARING_STAFF_OF = "清理杖"
STRINGS.RECIPE_DESC.CLEARING_STAFF_OF = "无法制作的,是其他mod添加到制作栏啦" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLEARING_STAFF_OF = "清除一定范围内的物品(半径1地皮)"

STRINGS.NAMES.GAMBLING_OF = "赌博机"
STRINGS.RECIPE_DESC.GAMBLING_OF = "无法制作的,是其他mod添加到制作栏啦" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GAMBLING_OF = "将物资45%概率额外生成1~3个新物品（属性继承原来的），55%概率直接删掉"

STRINGS.NAMES.SPRINGLAMP = "泉灯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPRINGLAMP = "小心，放别太满了"

-- 包裹显示名称
STRINGS.NAMES.CAVELIGHT = "洞穴光"
STRINGS.NAMES.DROPPERWEB = "白色蜘蛛网巢穴"
STRINGS.NAMES.FISSURE = "梦魇裂隙"
STRINGS.NAMES.FISSURE_LOWER = "梦魇裂隙"
STRINGS.NAMES.FISSURE_GROTTOWAR = "梦魇裂隙"
STRINGS.NAMES.MIASMA_CLOUD = "瘴气"
STRINGS.NAMES.RUINS_STATUE_MAGE = "远古雕像"
STRINGS.NAMES.ATRIUM_IDOL = "远古方尖碑"

STRINGS.ACTIONS.RELINQUISHCONTROL = "取消控制"

--兼容能力勋章显示buff名称 添加移除buff会提示
local buffs = {
    BUFF_ATTACK_OF = "侵掠如火",
    BUFF_PLAYERABSORPTION_OF = "固若金汤",
    BUFF_BLEED_OF = "流血",
    BUFF_REDUCESAN_OF = "降智",
    BUFF_SIPPING_OF = "啜食",
    BUFF_REFUSEFISH_OF = "禁渔期",
    BUFF_FEETSLIPPED_OF = "脚滑",
    BUFF_ALTERSELF_OF = "变身术",
    BUFF_RAPID_OF = "疾如风",
    BUFF_BIG_OF = "变大",
    BUFF_SMALL_OF = "变小",
    BUFF_DEATHRATTLE_OF = "亡语",
}
for buff, name in pairs(buffs) do
    STRINGS.CHARACTERS.GENERIC["ANNOUNCE_ATTACH_"..buff] = "添加了["..name.."]BUFF"
    STRINGS.CHARACTERS.GENERIC["ANNOUNCE_DETACH_"..buff] = "["..name.."]BUFF, 失效了"
    STRINGS.NAMES[buff] = name
end